<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="white">
  <div class="container-fluid">
<div class="page-header">
    <h3>
        แก้ไขข้อมูลส่วนตัว
    </h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "admin/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdteacher" class="col-sm-2 control-label">รหัสอาจารย์</label>
    <div class="col-sm-3">
      <?php echo $this->tag->hiddenField(["idTeacher", "type" => "number", "class" => "form-control", "id" => "fieldIdteacher"]) ?>
        <?php echo $this->tag->textField(["idTeacher", "type" => "number", "class" => "form-control", "id" => "fieldIdteacher","disabled"=>"disabled"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">คำนำหน้า</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(["Title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">ชื่อ</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(["FirstName", "size" => 30, "class" => "form-control", "id" => "fieldFirstname"]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldLastname" class="col-sm-2 control-label">นามสกุล</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(["LastName", "size" => 30, "class" => "form-control", "id" => "fieldLastname"]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">รหัสผ่าน</label>
    <div class="col-sm-3">
        <?php echo $this->tag->PasswordField(["Password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldStatus" class="col-sm-2 control-label">สถานะ</label>
    <div class="col-sm-5">
      <?php $teacher= Teacher::findFirstByidTeacher($idTeacher) ?>
      <input type="radio" name="status"  value="1" <?php if($teacher->status==1) {echo "checked";} ?>>&nbsp; ผู้ดูแลระบบ&nbsp;&nbsp;&nbsp;&nbsp;
      <input type="radio" name="status"  value="0" <?php if($teacher->status==0) {echo "checked";} ?>>&nbsp; อาจารย์&nbsp;&nbsp;&nbsp;&nbsp;
        <!-- <?php echo $this->tag->textField(["status", "type" => "number", "class" => "form-control", "id" => "fieldStatus"]) ?> -->
    </div>
</div>

<div class="form-group">
    <label for="fieldImage" class="col-sm-2 control-label">รูปภาพ</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(["image", "size" => 30, "class" => "form-control", "id" => "fieldImage"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <?php echo $this->tag->linkTo(["admin/search", "ยกเลิก","class"=>"btn btn-default"]); ?>
      <?php echo $this->tag->submitButton(["บันทึกการแก้ไข", "class" => "btn btn-default searchbut"]) ?>
    </div>
</div>

</div>
</div>

<?php echo $this->tag->endForm(); ?>
