<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>


<div class="white">
  <div class="container-fluid">

<div class="page-header">
    <h1>
        เพิ่มอาจารย์
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "admin/create",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "enctype" => "multipart/form-data"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdteacher" class="col-sm-2 control-label">รหัสอาจารย์</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(["idTeacher", "type" => "number", "class" => "form-control", "id" => "fieldIdteacher" , "placeholder" =>"รหัสอาจารย์" ,"required"=>""]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">คำนำหน้า</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(["Title", "size" => 30, "class" => "form-control", "id" => "fieldTitle", "placeholder" =>"คำนำหน้า" ,"required"=>""]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">ชื่อ</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(["FirstName", "size" => 30, "class" => "form-control", "id" => "fieldFirstname", "placeholder" =>"ชื่อ" ,"required"=>""]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>

</div>

<div class="form-group">
  <label for="fieldLastname" class="col-sm-2 control-label">นามสกุล</label>
    <div class="col-sm-3">
      <?php echo $this->tag->textField(["LastName", "size" => 30, "class" => "form-control", "id" => "fieldLastname","placeholder" =>"นามสกุล" ,"required"=>""]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>


<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">รหัสผ่าน</label>
    <div class="col-sm-3">
        <?php echo $this->tag->passwordField(["Password", "size" => 30, "class" => "form-control", "id" => "fieldPassword","placeholder" =>"รหัสผ่าน" ,"required"=>""]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldStatus" class="col-sm-2 control-label">สถานะ</label>
    <div class="col-sm-4">
      <input name="status" type="radio" value="0" checked="true">  อาจารย์&nbsp;&nbsp;
      <input name="status" type="radio" value="1">  ผู้ดูแลระบบ<br>
    </div>
</div>

<div class="form-group">
    <label for="fieldStatus" class="col-sm-2 control-label">รูปภาพ</label>
  <div class="col-md-7">
      <input type='file' id="imgInp" />
</div>
</div>
<div class="form-group hero">
  <div class="col-sm-3 col-sm-offset-2">
    <?php echo $this->tag->linkTo(["admin/search", "ยกเลิก","class"=>"btn btn-default"]); ?>
    <?php echo $this->tag->submitButton([" เพิ่มอาจารย์", "class" => "btn btn-success"]) ?>
  </div>
</div>
</div>
</div>


<?php echo $this->tag->endForm(); ?>
