<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="page-header">
    <h1>นักศึกษา</h1>
</div>






<!--
            <div class="col-md-12 white">

                    <div class="panel-body">
                      <table id="mytable" class="table">
                            <thead>
                            <tr>
                                <th class="text-center" >No.</th>
                                <th class="col-text text-center">รูปภาพ</th>
                                <th class="col-text text-center">คำนำหน้า</th>
                                <th class="col-tools text-center">ชื่อ-สกุล</th>
                                <th class="col-tools text-center">สถานะ</th>
                                <th class="col-tools text-center">จัดการผู้ใช้</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr data-status="completed">
                                <td class="text-center">1</td>
                                <td class="text-center"><img src="https://s3.amazonaws.com/uifaces/faces/twitter/fffabs/128.jpg" class="userpic"></td>
                                <td class="text-center">อาจารย์ ดร.</td>
                                <td class="text-center">พุฒิพร ธนธรรมเมธี</td>
                                <td class="text-center">อาจารย์</td>
                                <td align="center">
                                    <a class="btn btn-primary">แก้ไข</a>
                                    <a class="btn btn-danger butdanger">ลบ</a>
                                </td>
                            </tr>
                            <tr data-status="completed">
                                <td class="text-center">1</td>
                                <td class="text-center"><img src="https://s3.amazonaws.com/uifaces/faces/twitter/fffabs/128.jpg" class="userpic"></td>
                                <td class="text-center">อาจารย์ ดร.</td>
                                <td class="text-center">พุฒิพร ธนธรรมเมธี</td>
                                <td class="text-center">อาจารย์</td>
                                <td align="center">
                                    <a class="btn btn-primary">แก้ไข</a>
                                    <a class="btn btn-danger butdanger">ลบ</a>
                                </td>
                            </tr>

                            </tbody>
                        </table>

                    </div>


            </div> -->
