
<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>
<div class="page-header">
    <h1>รายชื่อนักศึกษา</h1>
</div>

<div class="col-md-12 col-md-offset-0">

    <div class="fresh-table toolbar-color-azure white">


        <table id="fresh-table" class="table">
            <thead>
              <th>รูปภาพ</th>

              <th data-field="idStudent" data-sortable="true">รหัสนักศึกษา</th>
              <th data-field="Title" data-sortable="true">คำนำหน้า</th>
              <th data-field="FirstName" data-sortable="true">ชื่อ - สกุล</th>

              <th data-field="year" data-sortable="true">ชั้นปี</th>
              <th data-field="actions" data-events="operateEvents">ประวัติการเข้าร่วมกิจกรรม</th>


            </thead>
            <tbody>
                  <?php foreach ($page->items as $student):?>
                <tr>
                  <td class="text-center"><img src="../<?php echo $student->image ; ?>" class="userpic img-circle"></td>

                  <td class="text-center"><?php echo $student->idStudent ?></td>
                  <td><?php echo $student->Title ?></td>
                  <td><?php echo $student->FirstName." ".$student->LastName ?></td>
                  <td><?php echo $student->year ?></td>
                  <td>
                    <?php echo $this->tag->linkTo(["admin/joinac/" . $student->idStudent, "การเข้าร่วมกิจกรรม","class"=>"btn btn-default searchbut"]); ?>
                  </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>


</div>
	<!-- <div class="row">
        <div class="col-sm-6">
            <div class="business-card">
                <div class="media">
                    <div class="media-left">
                        <img class="media-object img-circle profile-img" src="http://s3.amazonaws.com/37assets/svn/765-default-avatar.png">
                    </div>
                    <div class="media-body">
                        <h2 class="media-heading">Daniel</h2>
                        <div class="job">CEO</div>
                        <div class="mail"><a href="mailto:daniel@bla.ch">daniel@bla.ch</a> </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="business-card">
                <div class="media">
                    <div class="media-left">
                        <img class="media-object img-circle profile-img" src="http://s3.amazonaws.com/37assets/svn/765-default-avatar.png">
                    </div>
                    <div class="media-body">
                        <h2 class="media-heading">Daniel</h2>
                        <div class="job">CEO</div>
                        <div class="mail"><a href="mailto:daniel@bla.ch">daniel@bla.ch</a> </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="business-card">
                <div class="media">
                    <div class="media-left">
                        <img class="media-object img-circle profile-img" src="http://s3.amazonaws.com/37assets/svn/765-default-avatar.png">
                    </div>
                    <div class="media-body">
                        <h2 class="media-heading">Daniel</h2>
                        <div class="job">CEO</div>
                        <div class="mail"><a href="mailto:daniel@bla.ch">daniel@bla.ch</a> </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="business-card">
                <div class="media">
                    <div class="media-left">
                        <img class="media-object img-circle profile-img" src="http://s3.amazonaws.com/37assets/svn/765-default-avatar.png">
                    </div>
                    <div class="media-body">
                        <h2 class="media-heading">Samuel</h2>
                        <div class="job">Business Development</div>
                        <div class="mail"><a href="mailto:samuel@bla.ch">samuel@bla.ch</a> </div>
                    </div>
                </div>
            </div>
        </div>
	</div> -->
