<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>


<div class="white">
  <div class="container-fluid">

<div class="page-header">
    <h3>
        แก้ไขข้อมูลนักศึกษา
    </h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "admin/stsave",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdstudent" class="col-sm-2 control-label">รหัสนักศึกษา</label>
    <div class="col-sm-4">
        <?php echo $this->tag->hiddenField(["idStudent", "size" => 30, "class" => "form-control", "id" => "fieldIdstudent"]) ?>
        <?php echo $this->tag->textField(["idStudent", "size" => 30, "class" => "form-control", "id" => "fieldIdstudent","disabled"=>"disabled"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">คำนำหน้า</label>
    <div class="col-sm-4">
      <?php echo $this->tag->hiddenField(["Title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
        <?php echo $this->tag->textField(["Title", "size" => 30, "class" => "form-control", "id" => "fieldTitle","disabled"=>"disabled"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">ชื่อ</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["FirstName", "size" => 30, "class" => "form-control", "id" => "fieldFirstname"]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldLastname" class="col-sm-2 control-label">สกุล</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["LastName", "size" => 30, "class" => "form-control", "id" => "fieldLastname"]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">รหัสผ่าน</label>
    <div class="col-sm-4">
        <?php echo $this->tag->PasswordField(["Password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldYear" class="col-sm-2 control-label">ชั้นปี</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["year", "type" => "number", "class" => "form-control", "id" => "fieldYear"]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <?php echo $this->tag->linkTo(["admin/stsearch", "ยกเลิก","class"=>"btn btn-default"]); ?>
      <?php echo $this->tag->submitButton(["บันทึกการแก้ไข", "class" => "btn btn-default searchbut"]) ?>
    </div>
</div>
</div>
</div>
<?php echo $this->tag->endForm(); ?>
