<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>



<div class="white">
  <div class="container-fluid">

<div class="page-header">
    <h2>
        เพิ่มนักศึกษา
    </h2>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "admin/stcreate",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdstudent" class="col-sm-2 control-label">รหัสนักศึกษา</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["idStudent", "size" => 30, "class" => "form-control", "id" => "fieldIdstudent" , "placeholder" =>"นักศึกษา" ,"required"=>""]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">คำนำหน้า</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["Title", "size" => 30, "class" => "form-control", "id" => "fieldTitle", "placeholder" =>"คำนำหน้า" ,"required"=>""]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">ชื่อ</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["FirstName", "size" => 30, "class" => "form-control", "id" => "fieldFirstname" , "placeholder" =>"ชื่อ" ,"required"=>""]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldLastname" class="col-sm-2 control-label">นามสกุล</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["LastName", "size" => 30, "class" => "form-control", "id" => "fieldLastname", "placeholder" =>"นามสกุล" ,"required"=>""]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>

<div class="form-group">
    <label for="fieldYear" class="col-sm-2 control-label">ชั้นปี</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["year", "type" => "number", "class" => "form-control", "id" => "fieldYear", "placeholder" =>"ชั้นปี" ,"required"=>""]) ?>
    </div>&nbsp;<font color="red" size="5">*</font>
</div>


<div class="form-group hero">
  <div class="col-sm-offset-2 col-sm-10">
    <?php echo $this->tag->linkTo(["admin/stsearch", "ยกเลิก","class"=>"btn btn-default"]); ?>
    <?php echo $this->tag->submitButton([" เพิ่มอาจารย์", "class" => "btn btn-success"]) ?>
  </div>
</div>
</div>
</div>
<?php echo $this->tag->endForm(); ?>
