<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="page-header">
    <h1>นักศึกษา</h1>
</div>


<div class="pull-left marbot">
  <?php echo $this->tag->linkTo(["admin/student", "ค้นหานักศึกษา","class"=>"btn btn-default"]); ?>
  <?php echo $this->tag->linkTo(["admin/stsearch", "แสดงนักศึกษาทั้งหมด","class"=>"btn btn-warning"]); ?>
</div>

<div class="pull-right marbot">
  <?php echo $this->tag->linkTo(["admin/stnew", "เพิ่มนักศึกษา","class"=>"btn btn-success"]); ?>
</div>


<?php echo $this->getContent(); ?>
<div class="col-md-12 white">
  <div class="panel-body">
    <table id="mytable" class="table table-hover fresh-table">
        <thead>
            <tr>
              <th>รูปภาพ</th>
              <th>รหัสนักศึกษา</th>
            <th>คำนำหน้า</th>
            <th class="text-center" >ชื่อ-สกุล</th>
            <th width="10%">ปีการศึกษา</th>
            <th width="10%">ชั้นปี</th>
            <th class="text-center" >จัดการผู้ใช้</th>

            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $student): ?>
            <tr>

            <td><img src="<?php echo $student->image ; ?>" class="userpic img-circle"></td>
            <td width="15%"><?php echo $student->idStudent ?></td>
            <td width="10%"><?php echo $student->Title ?></td>
            <td><?php echo $student->FirstName," ",$student->LastName ?></td>
            <td><?php echo $student->year ?></td>
            <td><?php echo (2560-$student->year+1) ?></td>
            <td class="text-center" >
              <?php echo $this->tag->linkTo(["admin/stedit/" .$student->idStudent, "แก้ไข","class"=>"btn btn-default"]); ?>
              <?php echo $this->tag->linkTo(["admin/stdelete/" .$student->idStudent, "ลบผู้ใช้","class"=>"btn btn-danger danger"]); ?>

            </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("admin/stsearch", "First") ?></li>
                <li><?php echo $this->tag->linkTo("admin/stsearch?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("admin/stsearch?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("admin/stsearch?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
</div>
