<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<div class="white">
  <div class="container-fluid">
<div class="page-header">
    <h2>
        ค้นหานักศึกษา
    </h2>

</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "admin/stsearch",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdstudent" class="col-sm-2 control-label">รหัสนักศึกษา</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["idStudent", "size" => 30, "class" => "form-control", "id" => "fieldIdstudent", "placeholder" =>"รหัสนักศึกษา"]) ?>
    </div>
</div>


<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">ชื่อ</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["FirstName", "size" => 30, "class" => "form-control", "id" => "fieldFirstname", "placeholder" =>"ชื่อ"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastname" class="col-sm-2 control-label">นามสกุล</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["LastName", "size" => 30, "class" => "form-control", "id" => "fieldLastname", "placeholder" =>"นามสกุล"]) ?>
    </div>
</div>



<div class="form-group">
    <label for="fieldYear" class="col-sm-2 control-label">ชั้นปี</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["year", "type" => "number", "class" => "form-control", "id" => "fieldYear", "placeholder" =>"ชั้นปี"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["ค้นหา", "class" => "btn btn-default"]) ?>
    </div>
</div>
</div>
</div>

<?php echo $this->tag->endForm(); ?>
