<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<div class="white">
  <div class="container-fluid">

    <div class="page-header">
      <center><h2>
        ค้นหาอาจารย์
      </h2></center>

    </div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "admin/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>
<div class="col-md-12 col-md-offset-2">
  <div class="form-group">
      <label for="fieldIdteacher" class="col-sm-2 control-label">รหัสอาจารย์</label>
      <div class="col-sm-4">
        <?php echo $this->tag->textField(["idTeacher", "type" => "number", "class" => "form-control", "id" => "fieldIdteacher", "placeholder" =>"รหัสอาจารย์"]) ?>
    </div>
  </div>

  <div class="form-group">
      <label for="fieldFirstname" class="col-sm-2 control-label">ชื่อ</label>
      <div class="col-sm-4">
        <?php echo $this->tag->textField(["FirstName", "size" => 30, "class" => "form-control", "id" => "fieldFirstname" , "placeholder" =>"ชื่อ"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastname" class="col-sm-2 control-label">นามสกุล</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["LastName", "size" => 30, "class" => "form-control", "id" => "fieldLastname", "placeholder" =>"นามสกุล"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["ค้นหา", "class" => "btn btn-default searchbut"]) ?>
    </div>
</div>
</div>
</div>
</div>

<?php echo $this->tag->endForm(); ?>
