<div class="container">
  <div class="page-header">
    <h2>Add std</h2>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <form class="form-horizontal">
        <div class="form-group">
          <label for="FirstName" class="col-sm-2 control-label">FirstName</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="FirstName" placeholder="FirstName">
          </div>
        </div>
        <div class="form-group">
          <label for="LastName" class="col-sm-2 control-label">LastName</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="LastName" placeholder="LastName">
          </div>
        </div>
      </form>

      <form class="form-horizontal">
        <div class="form-group">
          <label for="IDstd" class="col-sm-2 control-label">ID Student</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" id="IDstd" placeholder="IDstd">
          </div>
          <label for="yearStd" class="col-sm-2 control-label">Year</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" id="yearStd" placeholder="Year">
          </div>
        </div>
      </form>

      <form class="form-horizontal">
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <label for="exampleInputFile">Image</label>
            <input type="file" id="Image">
            <p class="help-block"></p>
        </div>
        </div>
      </form>

      <form class="form-horizontal">
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Save</button>
          </div>
        </div>
      </form>

    </div>
  </div>
</div>
