  <div class="cover">
  </div>

<div class="container w-nav">
    <div class="page-header">
        <h3>กิจกรรมเสริมหลักสูตร วิศวกรรมซอฟต์แวร์</h3>
    </div>


    <div class="row">

      <?php $ac=activity::findFirstByidActivity( 21 ); ?>

      <a href="student/showac/21"><div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <img src="public/img/activity/7.jpg" alt="..." class="size image-rounded">
          <div class="caption">
            <h3><?php echo $ac->ActivityName ?></h3>
            <hr>
            <p><span><?php echo "Start"." ".$ac->StartDate  ?></span>
            <br>
            <span><?php echo "End"." ".$ac->EndDate  ?></span></p>
            <p>  <?php $teacherId=teacher::findFirstByidTeacher( $ac->Teacher_idTeacher ); ?>
              <?php echo "อาจารย์ผู้รับผิดชอบ"." ".$teacherId->Title." ".$teacherId->FirstName." ".$teacherId->LastName ?>
            </p>
          </div>
        </div>
      </div></a>


      <?php $ac=activity::findFirstByidActivity( 19 ); ?>
      <a href="student/showac/19"><div class="col-sm-6 col-md-4">
        <div class="thumbnail">
        <img src="public/img/activity/11.jpg" alt="..." class="size image-rounded">
        <div class="caption">
            <h3><?php echo $ac->ActivityName ?></h3>
            <hr>
            <p><span><?php echo "Start"." ".$ac->StartDate  ?></span>
            <br>
            <span><?php echo "End"." ".$ac->EndDate  ?></span></p>
            <p>  <?php $teacherId=teacher::findFirstByidTeacher( $ac->Teacher_idTeacher ); ?>
              <?php echo "อาจารย์ผู้รับผิดชอบ"." ".$teacherId->Title." ".$teacherId->FirstName." ".$teacherId->LastName ?>
            </p>
          </div>
        </div>
      </div></a>


      <?php $ac=activity::findFirstByidActivity( 18 ); ?>
      <a href="student/showac/18"><div class="col-sm-6 col-md-4">
        <div class="thumbnail">
        <img src="public/img/activity/9.jpg" alt="..." class="size image-rounded">
          <div class="caption">
            <h3><?php echo $ac->ActivityName ?></h3>
            <hr>
            <p><span><?php echo "Start"." ".$ac->StartDate  ?></span>
            <br>
            <span><?php echo "End"." ".$ac->EndDate  ?></span></p>
            <p>  <?php $teacherId=teacher::findFirstByidTeacher( $ac->Teacher_idTeacher ); ?>
              <?php echo "อาจารย์ผู้รับผิดชอบ"." ".$teacherId->Title." ".$teacherId->FirstName." ".$teacherId->LastName ?>
            </p>
          </div>
        </div>
      </div></a>



    </div>

    <div class="row">

      <?php $ac=activity::findFirstByidActivity( 15 ); ?>
      <a href="student/showac/21"><div class="col-sm-6 col-md-4">
        <div class="thumbnail">
        <img src="public/img/activity/13.jpg" alt="..." class="size image-rounded">
          <div class="caption">
            <h3><?php echo $ac->ActivityName ?></h3>
            <hr>
            <p><span><?php echo "Start"." ".$ac->StartDate  ?></span>
            <br>
            <span><?php echo "End"." ".$ac->EndDate  ?></span></p>
            <p>  <?php $teacherId=teacher::findFirstByidTeacher( $ac->Teacher_idTeacher ); ?>
              <?php echo "อาจารย์ผู้รับผิดชอบ"." ".$teacherId->Title." ".$teacherId->FirstName." ".$teacherId->LastName ?>
            </p>
          </div>
        </div>
      </div></a>


      <?php $ac=activity::findFirstByidActivity( 10 ); ?>
      <a href="student/showac/10"><div class="col-sm-6 col-md-4">
        <div class="thumbnail">
        <img src="public/img/activity/2.jpg" alt="..." class="size image-rounded">
          <div class="caption">
            <h3><?php echo $ac->ActivityName ?></h3>
            <hr>
            <p><span><?php echo "Start"." ".$ac->StartDate  ?></span>
            <br>
            <span><?php echo "End"." ".$ac->EndDate  ?></span></p>
            <p>  <?php $teacherId=teacher::findFirstByidTeacher( $ac->Teacher_idTeacher ); ?>
              <?php echo "อาจารย์ผู้รับผิดชอบ"." ".$teacherId->Title." ".$teacherId->FirstName." ".$teacherId->LastName ?>
            </p>
          </div>
        </div>
      </div></a>


      <?php $ac=activity::findFirstByidActivity( 17 ); ?>
      <a href="student/showac/17"><div class="col-sm-6 col-md-4">
        <div class="thumbnail">
        <img src="public/img/activity/3.jpg" alt="..." class="size image-rounded">
          <div class="caption">
            <h3><?php echo $ac->ActivityName ?></h3>
            <hr>
            <p><span><?php echo "Start"." ".$ac->StartDate  ?></span>
            <br>
            <span><?php echo "End"." ".$ac->EndDate  ?></span></p>
            <p>  <?php $teacherId=teacher::findFirstByidTeacher( $ac->Teacher_idTeacher ); ?>
              <?php echo "อาจารย์ผู้รับผิดชอบ"." ".$teacherId->Title." ".$teacherId->FirstName." ".$teacherId->LastName ?>
            </p>
          </div>
        </div>
      </div></a>



    </div>

    <!-- <div class="row" style="margin-bottom: 20px; margin-top:20px;">
      <?php $ac=activity::findFirstByidActivity( 21 ); ?>
      <div class="col-sm-6 col-md-6">
        <div class="">

          <div class="col-md-4" style="padding-left : 0px" class="box">
            <img src="https://cdn-images-1.medium.com/max/800/1*-idr0gCmklKx3cxRRXkk4A.jpeg" alt="..." class="hhh size img-rounded">
          </div>
          <div class="col-md-6">

              <h5><b><?php echo $ac->ActivityName ?></b></h5>
              <p><hr />
              <span><?php echo "Start"." ".$ac->StartDate  ?></span>
              <br>
              <span><?php echo "End"." ".$ac->EndDate  ?></span>
             </p>

          </div>

        </div>
      </div>

      <?php $ac=activity::findFirstByidActivity( 2 ); ?>
      <div class="col-sm-6 col-md-6">
        <div class="">
          <div class="col-md-4" style="padding-left : 0px" class="box">
            <img src="https://cdn-images-1.medium.com/max/800/1*-idr0gCmklKx3cxRRXkk4A.jpeg" alt="..." class="hhh size img-rounded">
          </div>
          <div class="col-md-6">

              <h5><b><?php echo $ac->ActivityName ?></b></h5>
              <p><hr />
              <span><?php echo "Start"." ".$ac->StartDate  ?></span>
              <br>
              <span><?php echo "End"." ".$ac->EndDate  ?></span>
             </p>

          </div>

        </div>
      </div>

</div>
<div class="row">
  <?php $ac=activity::findFirstByidActivity( 21 ); ?>
  <div class="col-sm-6 col-md-6">
    <div class="">

      <div class="col-md-4" style="padding-left : 0px" class="box">
        <img src="https://cdn-images-1.medium.com/max/800/1*-idr0gCmklKx3cxRRXkk4A.jpeg" alt="..." class="hhh size img-rounded">
      </div>
      <div class="col-md-6">

          <h5><b><?php echo $ac->ActivityName ?></b></h5>
          <p><hr />
          <span><?php echo "Start"." ".$ac->StartDate  ?></span>
          <br>
          <span><?php echo "End"." ".$ac->EndDate  ?></span>
         </p>

      </div>

    </div>
  </div>

  <?php $ac=activity::findFirstByidActivity( 2 ); ?>
  <div class="col-sm-6 col-md-6">
    <div class="">
      <div class="col-md-4" style="padding-left : 0px" class="box">
        <img src="https://cdn-images-1.medium.com/max/800/1*-idr0gCmklKx3cxRRXkk4A.jpeg" alt="..." class="hhh size img-rounded">
      </div>
      <div class="col-md-6">

          <h5><b><?php echo $ac->ActivityName ?></b></h5>
          <p><hr />
          <span><?php echo "Start"." ".$ac->StartDate  ?></span>
          <br>
          <span><?php echo "End"." ".$ac->EndDate  ?></span>
         </p>

      </div>

    </div>
  </div>

</div> -->
  <!-- <div class ="col-md-6 col-sm-12 col-xs-12 out">
    <div class="col-md-12 bot">
      <div class="col-md-5 picbox u-sizeFullHeight">
      </div>
      <div class="col-md-7 textbox ">
        <h4>Software Activity In the major</h4>
      </div>
    </div>
  </div> -->

  <!-- <div class ="col-md-6 col-sm-12 col-xs-12 out">
    <div class="col-md-12 bot">
      <div class="col-md-5 picbox u-sizeFullHeight">
      </div>
      <div class="col-md-7 textbox ">
        <h4>Software Activity In the major</h4>
      </div>
    </div>
  </div>

  <div class ="col-md-6 col-sm-12 col-xs-12 out">
    <div class="col-md-12 bot">
      <div class="col-md-5 picbox u-sizeFullHeight">
      </div>
      <div class="col-md-7 textbox ">
        <h4>Software Activity In the major</h4>
      </div>
    </div>
  </div>

  <div class ="col-md-6 col-sm-12 col-xs-12 out">
    <div class="col-md-12 bot">
      <div class="col-md-5 picbox u-sizeFullHeight">
      </div>
      <div class="col-md-7 textbox ">
        <h4>Software Activity In the major</h4>
      </div>
    </div>
  </div> -->


<!--
  <div class="page-header">
      <h3>Coming Up program</h3>
  </div>

<?php $ac=activity::findFirstByidActivity( 21 ); ?>
<div class="col-md-12">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="panel panel-default panel-horizontal">
          <div class="panel-heading text-center">
            <div class="email" style="padding-top: 10px;">หลักสูตร</div>
            <span><h5>Software Engineering</h5><span>
              <hr />
              <span><?php echo "Start"." ".$ac->StartDate  ?></span>
              <br>
              <span><?php echo "End"." ".$ac->EndDate  ?></span>
          </div>
          <div class="panel-body">
            <div class="col-xs-12 col-md-12 section-box">
              <div class="email" style="padding-top: 10px;">
                กิจกรรมเสริมหลักสูตรสาขาวิชา Software Engineering
              </div>
              <h2><?php echo $ac->ActivityName ?><a href="http://bootsnipp.com/" target="_blank">
                <span class="glyphicon glyphicon-new-window"></span></a>
              </h2>
              <p>
              <?php echo $ac->Detail ?>
              </p>
              <hr />
              <div class="row rating-desc">
                <div class="col-md-12">
                  <span class="glyphicon glyphicon-comment"></span>|
                    <?php $teacherId=teacher::findFirstByidTeacher( $ac->Teacher_idTeacher ); ?>
                    <?php echo "อาจารย์ผู้รับผิดชอบ"." ".$teacherId->Title." ".$teacherId->FirstName." ".$teacherId->LastName ?>
                  <span class="separator">|</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<?php $ac=activity::findFirstByidActivity( 6 ); ?>
<div class="col-md-12">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="panel panel-default panel-horizontal">
          <div class="panel-heading text-center" >
            <div class="email" style="padding-top: 10px;">หลักสูตร</div>
            <span><h5>Software Engineering</h5><span>
              <hr />
              <span><?php echo "Start"." ".$ac->StartDate  ?></span>
              <br>
              <span><?php echo "End"." ".$ac->EndDate  ?></span>
          </div>
          <div class="panel-body">
            <div class="col-xs-12 col-md-12 section-box">
              <div class="email" style="padding-top: 10px;">
                กิจกรรมเสริมหลักสูตรสาขาวิชา Software Engineering
              </div>
              <h2><?php echo $ac->ActivityName ?><a href="http://bootsnipp.com/" target="_blank">
                <span class="glyphicon glyphicon-new-window"></span></a>
              </h2>
              <p>
              <?php echo $ac->Detail ?>
              </p>
              <hr />
              <div class="row rating-desc">
                <div class="col-md-12">
                  <span class="glyphicon glyphicon-comment"></span>|
                    <?php $teacherId=teacher::findFirstByidTeacher( $ac->Teacher_idTeacher ); ?>
                    <?php echo "อาจารย์ผู้รับผิดชอบ"." ".$teacherId->Title." ".$teacherId->FirstName." ".$teacherId->LastName ?>
                  <span class="separator">|</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> -->

<!--
<div class="col-md-12">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="panel panel-default panel-horizontal">
          <div class="panel-heading text-center" style="width:10em;">
            <span><h3>Homwwork</h3></span>
            <span>23 Jun 2017</span>
            <hr />
            <div class="email" style="padding-top: 10px;">css php html</div>
            <span><h5>Web programming</h5><span>
          </div>
          <div class="panel-body">
            <div class="col-xs-12 col-md-12 section-box">
              <div class="email" style="padding-top: 10px;">
                Web programming with phalcon
              </div>
              <h2>Project web programming <a href="http://bootsnipp.com/" target="_blank">
                <span class="glyphicon glyphicon-new-window"></span></a>
              </h2>
              <p>
                AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              </p>
              <hr />
              <div class="row rating-desc">
                <div class="col-md-12">
                  <span class="glyphicon glyphicon-comment"></span>|
                  สุดโหดการบ้าน web programming ที่ต้องส่งในวันที่ 23 นี้
                  โอ๋วกระสงฆ์ โถ่ว ถัง กาลามัง โถ้ย โคม phalcon เอ๋ย!!!!!
                  <span class="separator">|</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="col-md-12">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="panel panel-default panel-horizontal">
          <div class="panel-heading text-center" style="width:10em;">
            <span><h3>Homwwork</h3></span>
            <span>23 Jun 2017</span>
            <hr />
            <div class="email" style="padding-top: 10px;">css php html</div>
            <span><h5>Web programming</h5><span>
          </div>
          <div class="panel-body">
            <div class="col-xs-12 col-md-12 section-box">
              <div class="email" style="padding-top: 10px;">
                Web programming with phalcon
              </div>
              <h2>Project web programming <a href="http://bootsnipp.com/" target="_blank">
                <span class="glyphicon glyphicon-new-window"></span></a>
              </h2>
              <p>
                AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              </p>
              <hr />
              <div class="row rating-desc">
                <div class="col-md-12">
                  <span class="glyphicon glyphicon-comment"></span>|
                  สุดโหดการบ้าน web programming ที่ต้องส่งในวันที่ 23 นี้
                  โอ๋วกระสงฆ์ โถ่ว ถัง กาลามัง โถ้ย โคม phalcon เอ๋ย!!!!!
                  <span class="separator">|</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> -->



</div>
