<?php $this->flashSession->output() ?>
<div class="login">
<div class="container">
	<div id="login-box" class="white">

		<div class="logo">
			<img src="../img/teamwork.png" class="img img-responsive img-circle center-block"/>
			<h1 class="logo-caption"><span class="tweak">L</span>ogin</h1>
		</div><!-- /.logo -->

		<?php
  echo $this->tag->form(
    [
      "Login/checklogin",
      "autocomplete" => "off",
      "class" => "form-horizontal"
    ]
  );
?>
		<div class="controls">
		<?php echo $this->tag->textField(["id", "size" => 30, "class" => "form-control", "required"=>"", "placeholder"=>"ชื่อผู้ใช้งาน"]) ?>
		<?php echo $this->tag->passwordField(["Password", "size" => 30, "class" => "form-control", "required"=>"", "placeholder"=>"รหัสผ่าน"]) ?>
		<?php echo $this->tag->submitButton(["เข้าสู่ระบบ", "class" => "btn btn-default btn-block btn-custom"]) ?>
		<?php echo $this->tag->linkTo(["home","กลับ","class" => "btn btn-default btn-block btn-custom"]) ?>
		</div><!-- /.controls -->
		<?php echo $this->tag->endForm(); ?>
	</div><!-- /#login-box -->
</div><!-- /.container -->
<div id="particles-js"></div>
</div>
<!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/particles.js/2.0.0/particles.min.js"></script>-->
